[phases.setup]
nixPkgs = ["python39", "postgresql", "gcc"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120" 